### PR TITLE
Add MessageLoop::SetTimer API

### PR DESCRIPTION
**Pull request by Frityet**
✅ By sending this pull request, I agree to the [Contributor License Agreement](https://github.com/yue/yue/tree/5079c44#contributor-license-agreement) of this project .

This solves #169.

## Motivating example

```lua
local gui = require("yue.gui")
local https = require("https") --example http library, uses coroutines

local window = gui.Window.create {}
local container = gui.Container.create()
container:setstyle {
    padding = 10
}

local label = gui.Label.create "Bytes downloaded: 0KB"
container:addchildview(label)

local progress = gui.ProgressBar.create()
container:addchildview(label)

local thr, total = https.get "https://big.url/really-big-file.bin"


gui.MessageLoop.enqueuedelayedtask(10, function ()
    if coroutine.status(thr) == "dead" then return false end
    local size = coroutine.resume(thr)
    label:settext("Bytes downloaded: "..(size/1000).."KB")
    progress:setvalue(size / total * 100)
    return true
end)

window:setcontentview(container)
window:setcontentsize(container:getpreferredsize())
window:activate()

gui.MessageLoop.run()
```

### CODE REVIEW

**Review by zcbenz — COMMENTED** [review]
I think the `EnqueueTask` API without timeout should be removed, it does not seem to have any practical use case.

And `EnqueueDelayedTask` can then be renamed to something like `SetTimer`, which is used more commonly in other libraries.

**Comment by Frityet** [comment]
> I think the `EnqueueTask` API without timeout should be removed, it does not seem to have any practical use case.
> 
> And `EnqueueDelayedTask` can then be renamed to something like `SetTimer`, which is used more commonly in other libraries.

Will do the rename, but the without timeout is something I actually do use.

This is how I actually use it in my code:
```lua

--runs when the event loop is ready
timer.setTimeout(0, function()
    uv.stop()

    utilities.enqueue(function()
        uv.run("nowait")
        return true
    end)

    gui.MessageLoop.run()
end)
```

Where the `timer` runs right as the file ends

**Comment by Frityet** [comment]
@zcbenz Ready for merge, I agree with you that the `SetTimer` with no delay has no use

**Review by zcbenz — APPROVED** [review]
Thanks!

**Pull request merged**
